name:                bencoding
version:             0.1.0.0
github:              "alios/bencoding"
license:             BSD3
author:              "Markus Barenhoff"
maintainer:          "mbarenh@alios.org"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alios/bencoding#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- text
- vector

library:
  source-dirs: src
  dependencies:
  - attoparsec
  - bytestring
  - containers
  ghc-options:
  - -Wall

tests:
  bencoding-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bencoding
    - QuickCheck
    - hspec
